server:
  port: ${PORT:8083}
spring:
  application:
    name: best-hotels
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/best_hotels
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
ribbon:
  eureka:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8080}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2